Add bookings
fixercom/java-shareit pull request #3
Opened 2023-02-21 13:14 UTC by fixercom

2023-02-22 15:37 UTC, krylov-sergey-sergeevich requested changes
Привет, очень неплохая работа. Давай кое что улучшим и будет зачет =)

2023-02-22 15:37 UTC, krylov-sergey-sergeevich commented on src/main/resources/schema.sql
> +    CONSTRAINT FK_ITEMS_ON_OWNER FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE CASCADE
CONSTRAINT FK_ITEM_ON_REQUEST FOREIGN KEY (request_id) REFERENCES item_requests (item_request_id),
CONSTRAINT UQ_OWNER_ITEM_NAME UNIQUE(owner_id, name)

Что нибудь такое можно вроде как добавить, что думаешь?

2023-02-22 15:37 UTC, krylov-sergey-sergeevich commented on src/main/resources/schema.sql
> +    status     VARCHAR(255)                            NOT NULL,
255 слишком большое число, там же енам вроде 15-20 хватит

2023-02-23 05:22 UTC, fixercom commented on src/main/resources/schema.sql
> +    status     VARCHAR(255)                            NOT NULL,
Явно переборщил:) поправил

2023-02-23 05:28 UTC, fixercom commented on src/main/resources/schema.sql
> +    CONSTRAINT FK_ITEMS_ON_OWNER FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE CASCADE
Привет! Очень даже логично, добавил ограничения.

2023-02-24 17:38 UTC, krylov-sergey-sergeevich approved these changes
Привет, вижу правки - зачет

2023-02-24 17:38 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/item/entity/Item.java
> +                @UniqueConstraint(name = "uc_items_name_owner", columnNames = {"name", "owner_id"})
Интересные штуки и подход вот так писать, но я лично опасаюсь, обычно чисто в sql описываю и все, но это мой личный кхм пунктик

2023-02-24 17:38 UTC, krylov-sergey-sergeevich commented on src/main/resources/schema.sql
> +    created      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
лучше обычно такое поле называть date_created

2023-02-25 08:22 UTC, merged