Add item requests
fixercom/java-shareit pull request #5
Opened 2023-03-07 13:50 UTC by fixercom

2023-03-08 06:38 UTC, krylov-sergey-sergeevich requested changes
Привет :) В целом отличный pr, но есть вопрос:

- Почему в тестах появляются @SneakyThrows, без них не выходит?

2023-03-08 06:38 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/request/ItemRequestController.java
> +    ItemRequestDtoOut createItemRequest(@RequestHeader(HeaderName.SHARER_USER_ID) Long userId,
public

2023-03-08 06:38 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/request/ItemRequestController.java
> +    List<ItemRequestDtoOut> getAllOwnItemRequests(@RequestHeader(HeaderName.SHARER_USER_ID) Long userId,
public

2023-03-08 06:38 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/request/ItemRequestController.java
> +    List<ItemRequestDtoOut> getAllNotOwnItemRequests(@RequestHeader(HeaderName.SHARER_USER_ID) Long userId,
public...

2023-03-08 06:38 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +    public User getUserEntityById(Long userId) {
Entity в название не обязательно

2023-03-08 06:38 UTC, krylov-sergey-sergeevich commented on src/test/java/ru/practicum/shareit/booking/dto/BookingDtoForItemTest.java
> +    private static final DateTimeFormatter FORMATTER = DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ss");
Эта штука просится в класс Constants

2023-03-08 08:52 UTC, fixercom commented
> * естах появляются @SneakyThrows, без них не выходит?

2023-03-08 08:57 UTC, fixercom commented on src/main/java/ru/practicum/shareit/request/ItemRequestController.java
> +    ItemRequestDtoOut createItemRequest(@RequestHeader(HeaderName.SHARER_USER_ID) Long userId,
Поправил

2023-03-08 08:59 UTC, fixercom commented on src/main/java/ru/practicum/shareit/request/ItemRequestController.java
> +    List<ItemRequestDtoOut> getAllOwnItemRequests(@RequestHeader(HeaderName.SHARER_USER_ID) Long userId,
Поправил

2023-03-08 08:59 UTC, fixercom commented on src/main/java/ru/practicum/shareit/request/ItemRequestController.java
> +    List<ItemRequestDtoOut> getAllNotOwnItemRequests(@RequestHeader(HeaderName.SHARER_USER_ID) Long userId,
Поправил

2023-03-08 09:34 UTC, fixercom commented
> Привет :) В целом отличный pr, но есть вопрос:
> 
> * Почему в тестах появляются @SneakyThrows, без них не выходит?

Привет Сергей! Я сначала без них сделал, но потом вышел вебинар по теме тестирование и там выступающий говорил добавим @SneakyThrows чтобы не пробрасывать исключения, я тогда подумал что нужно так делать и добавил их:) Сейчас убрал их и вернул назад throws Exception() после сигнатуры метода

2023-03-08 09:43 UTC, fixercom commented on src/test/java/ru/practicum/shareit/booking/dto/BookingDtoForItemTest.java
> +    private static final DateTimeFormatter FORMATTER = DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ss");
Перенес

2023-03-08 09:56 UTC, fixercom commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +    public User getUserEntityById(Long userId) {
Тут у меня такая ерунда получилась по следующей причине: изначально каждый сервис обращался к UserRepository для проверки пользователя, я подумал почему бы из других сервисов просто не вызывать UserService с готовой обработкой Optional<User>, чтобы каждый раз не писать .orElseThrow.... Но проблема оказалась в том что у меня уже есть метод getUserById, но он возвращает DTO объект (у меня в принципе все сервисы сразу возвращают dto), а мне нужен именно бизнес объект для дальнейшей работы с ним. Поэтому и создал второй метод с именем getUserEntityById(Long userId). Тоже сомнения закрадывались что то то не так. Вот и не могу понять как в итоге лучше быть, возможно решение внедрять зависимость на другой сервис изначально было не верным?

2023-03-09 06:20 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +    public User getUserEntityById(Long userId) {
Впринципе это верное решение (внедрять зависимости в другой сервис). Лично я в рабочих проектах просто возвращаю из сервисов не дто а ентити и это позволяет достаточно удобно взаимодействовать

2023-03-09 06:23 UTC, krylov-sergey-sergeevich approved these changes
Привет, вижу правки - зачет! На счет @SneakyThrows тут видимо кому как удобнее, плюсов его использования я не знаю, но возможно они есть...

2023-03-12 11:20 UTC, merged