Add docker
fixercom/java-shareit pull request #6
Opened 2023-03-17 05:05 UTC by fixercom

2023-03-17 05:29 UTC, fixercom commented
Привет Сергей! Для успешного прохождения тестов на своей локальной машине мне пришлось скорректировать время в докер контейнере share-it-server-container изменив Time Zone. Однако при пул реквесте тесты наоборот валятся, видно в них уже учитывается эта разность по времени, пришлось убрать изменение часового пояса. Я это просто к тому что если при локальной проверке часть тестов не будет работать надо откатить тогда последний коммит:)

2023-03-18 07:57 UTC, krylov-sergey-sergeevich requested changes
Привет, все хорошо, давай мелочи поправим и будет зачет =)

2023-03-18 07:57 UTC, krylov-sergey-sergeevich commented on shareIt-gateway/src/main/java/ru/practicum/shareit/booking/state/BookingState.java
> +    ALL, WAITING, PAST, CURRENT, FUTURE, REJECTED, UNSUPPORTED_STATUS
рекомендую 1 значение - 1 строка

2023-03-18 07:57 UTC, krylov-sergey-sergeevich commented on shareIt-gateway/src/main/java/ru/practicum/shareit/handler/GlobalExceptionHandler.java
> +    private static final String YELLOW_COLOR_LOG = "\033[33m";
вообще нет смысла на самом деле давать цвета логам, в реальных проектах логи все равно идут в специальный инструмент и они там все черные =)

2023-03-18 07:57 UTC, krylov-sergey-sergeevich commented on shareIt-gateway/src/test/java/ru/practicum/shareit/item/ItemControllerTest.java
> +    private static final String H_SHARER_USER_ID_IS_ABSENT_MESSAGE = "Required request header 'X-Sharer-User-Id'" +
Вроде бы несколько раз точно повторяется

2023-03-18 07:57 UTC, krylov-sergey-sergeevich commented on shareIt-server/src/main/resources/schema.sql
> +    text         VARCHAR(1000)                           NOT NULL,
text - не лучшее название поля, но не критично

2023-03-18 07:57 UTC, krylov-sergey-sergeevich commented on shareIt-server/src/test/java/ru/practicum/shareit/item/service/ItemServiceImplIntegrationTest.java
> +                .start(LocalDateTime.now().minusDays(1))
Рекомендую использовать вместо LocalDateTime свой утилитный класс DateUtils и там сделать статичный метод now() и использовать его во всем приложение.

2023-03-18 08:26 UTC, fixercom commented on shareIt-gateway/src/main/java/ru/practicum/shareit/booking/state/BookingState.java
> +    ALL, WAITING, PAST, CURRENT, FUTURE, REJECTED, UNSUPPORTED_STATUS
Исправил

2023-03-18 08:38 UTC, fixercom commented on shareIt-gateway/src/main/java/ru/practicum/shareit/handler/GlobalExceptionHandler.java
> +    private static final String YELLOW_COLOR_LOG = "\033[33m";
Убрал цвет

2023-03-18 08:47 UTC, fixercom commented on shareIt-gateway/src/test/java/ru/practicum/shareit/item/ItemControllerTest.java
> +    private static final String H_SHARER_USER_ID_IS_ABSENT_MESSAGE = "Required request header 'X-Sharer-User-Id'" +
Да, во всех тестах контроллера используется, перенес в класс Constants

2023-03-18 08:58 UTC, fixercom commented on shareIt-server/src/main/resources/schema.sql
> +    text         VARCHAR(1000)                           NOT NULL,
Изменил название на comment_text

2023-03-18 09:35 UTC, fixercom commented on shareIt-server/src/test/java/ru/practicum/shareit/item/service/ItemServiceImplIntegrationTest.java
> +                .start(LocalDateTime.now().minusDays(1))
Сделал, я правильно понимаю что это делается для того, чтобы в случае чего потом можно было быстро сменить логику получения текущего времени во всем проекте? Или для какой другой цели так делается?

2023-03-19 09:19 UTC, krylov-sergey-sergeevich commented on shareIt-server/src/test/java/ru/practicum/shareit/item/service/ItemServiceImplIntegrationTest.java
> +                .start(LocalDateTime.now().minusDays(1))
Именно для этого

2023-03-19 09:35 UTC, krylov-sergey-sergeevich approved these changes
Привет, вижу правки все хорошо - зачет!

2023-03-19 09:55 UTC, merged